version: '2.4'
services:

  router:
    image: "${ROUTER_DOCKER_IMAGE}"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - "${CARTO3_ONPREM_VOLUMES_BASE_PATH}certs/:/etc/nginx/ssl/:ro"
    env_file:
      - .env
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  accounts-www:
    image: "${ACCOUNTS_WWW_DOCKER_IMAGE}"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-www:
    image: "${WORKSPACE_WWW_DOCKER_IMAGE}"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-api:
    image: gcr.io/carto-artifacts/workspace-api:latest
    env_file:
      - .env
    depends_on:
      - workspace-postgres
      - workspace-migrations
      - redis
    command: npm run start:built
    volumes: &override-sa
      - "${CARTO3_ONPREM_VOLUMES_BASE_PATH}certs/:/usr/src/certs/:ro"
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-subscriber:
    image: gcr.io/carto-artifacts/workspace-api:latest
    command: npm run start:built:subscriber
    volumes: *override-sa
    env_file:
      - .env
    depends_on:
      - workspace-postgres
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-migrations:
    image: cloud-native_workspace-migrations:latest
    entrypoint: [ "/usr/src/app/onprem-init-db.sh"]
    env_file:
      - .env
    depends_on:
      - workspace-postgres
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  maps-api:
    image: gcr.io/carto-artifacts/maps-api:latest
    env_file:
      - .env
    depends_on:
      - workspace-postgres
      - redis
    command: npm run start:built
    volumes: *override-sa
    environment:
      - MAPS_API_V3_RESOURCE_URL_TEMPLATE_NEW=https://$${host}/api/$${path}
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  import-api:
    image: "${IMPORT_API_DOCKER_IMAGE}"
    env_file:
      - .env
    depends_on:
      - workspace-postgres
    command: npm run start:built
    volumes: *override-sa
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  import-worker:
    image: "${IMPORT_API_DOCKER_IMAGE}"
    volumes: *override-sa
    env_file:
      - .env
    depends_on:
      - workspace-postgres
    command: npm run start:built:subscriber
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  lds-api:
    image: gcr.io/carto-artifacts/lds-api:latest
    env_file:
      - .env
    depends_on:
      - workspace-postgres
    command: npm run start:built
    volumes: *override-sa
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-postgres:
    scale: "${LOCAL_POSTGRES_SCALE}"
    image: "postgres:13.2-alpine"
    env_file:
      - .env
    volumes:
      - workspace-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  redis:
    image: docker.io/bitnami/redis:5.0.14
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"
networks:
  default:

volumes:
  workspace-pgdata:
