version: "2.4"
services:
  router:
    image: "${ROUTER_DOCKER_IMAGE}"
    ports:
      - 80:8080
      - 443:8443
    restart: unless-stopped
    volumes:
      - "${CARTO3_SELFHOSTED_VOLUMES_BASE_PATH}certs/:/etc/nginx/ssl/:ro"
    env_file:
      - .env
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  http-cache:
    image: "${HTTP_CACHE_DOCKER_IMAGE}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - maps-api
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"
  notifier:
    image: "${NOTIFIER_DOCKER_IMAGE}"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - workspace-api
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  accounts-www:
    image: "${ACCOUNTS_WWW_DOCKER_IMAGE}"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-www:
    image: "${WORKSPACE_WWW_DOCKER_IMAGE}"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-api:
    image: "${WORKSPACE_API_DOCKER_IMAGE}"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024
    depends_on:
      - workspace-migrations
    command: bash -c "npm run ready-to-run:built && exec node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/index.js"
    volumes: &default-volumes
      - "${CARTO3_SELFHOSTED_VOLUMES_BASE_PATH}certs/:/usr/src/certs/:ro"
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-subscriber:
    image: "${WORKSPACE_API_DOCKER_IMAGE}"
    command: bash -c "npm run ready-to-run:built && exec node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/subscriber/index.js"
    volumes: *default-volumes
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-migrations:
    image: "${WORKSPACE_MIGRATIONS_DOCKER_IMAGE}"
    entrypoint: ["/usr/src/app/onprem-init-db.sh"]
    env_file:
      - .env
    volumes: *default-volumes
    restart: on-failure
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  maps-api:
    image: "${MAPS_API_DOCKER_IMAGE}"
    env_file:
      - .env
    command: bash -c "npm run ready-to-run:built && exec node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/index.js"
    volumes: *default-volumes
    environment:
      - MAPS_API_V3_RESOURCE_URL_TEMPLATE_NEW=https://$${host}/api/$${path}
      - NODE_OPTIONS=--max-old-space-size=1875
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  sql-worker:
    image: "${MAPS_API_DOCKER_IMAGE}"
    env_file:
      - .env
    command: bash -c "npm run ready-to-run:built && exec node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/subscriber/index.js"
    volumes: *default-volumes
    environment:
      - MAPS_API_V3_RESOURCE_URL_TEMPLATE_NEW=https://$${host}/api/$${path}
      - NODE_OPTIONS=--max-old-space-size=1536
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  cdn-invalidator-sub:
    image: "${CDN_INVALIDATOR_SUB_DOCKER_IMAGE}"
    command: node -r /usr/src/app/cdn-invalidator-sub/tsconfig-paths-bootstrap.js /usr/src/app/cdn-invalidator-sub/dist/app/cdn-invalidator-sub/index.js
    volumes: &default-volumes-double-level
      - "${CARTO3_SELFHOSTED_VOLUMES_BASE_PATH}certs/:/usr/src/app/certs/:ro"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  import-api:
    image: "${IMPORT_API_DOCKER_IMAGE}"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
    command: bash -c "npm run ready-to-run:built && exec node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/index.js"
    volumes: *default-volumes
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  import-worker:
    image: "${IMPORT_API_DOCKER_IMAGE}"
    volumes: *default-volumes
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    command: node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/subscriber/index.js
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  lds-api:
    image: "${LDS_API_DOCKER_IMAGE}"
    env_file:
      - .env
    environment:
      - NODE_OPTIONS=--max-old-space-size=768
    command: bash -c "npm run ready-to-run:built && exec node -r /usr/src/app/tsconfig-paths-bootstrap.js /usr/src/app/dist/app/index.js"
    volumes: *default-volumes
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  workspace-postgres:
    scale: "${LOCAL_POSTGRES_SCALE}"
    image: "postgres:13.2-alpine"
    env_file:
      - .env
    volumes:
      - workspace-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_ADMIN_PASSWORD
      - POSTGRES_USER=$POSTGRES_ADMIN_USER
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"

  redis:
    scale: "${LOCAL_REDIS_SCALE}"
    image: "redis:6.0-alpine"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "local"
      options:
        max-size: "5M"
        max-file: "20"
networks:
  default:

volumes:
  workspace-pgdata:
