name: Release - Automerge
on:
  pull_request:
    branches:
      - master
    paths:
      - VERSION

jobs:
  auto-merge-pr:
    runs-on: ubuntu-20.04
    name: "Automerge PR"
    steps:
      - name: Checkout cloud-native repository
        uses: actions/checkout@v3
        with:
          repository: CartoDB/cloud-native
          path: cloud-native
          token: ${{ secrets.X_GITHUB_CARTOFANTE }}
      - name: Automerge PR
        uses: ./cloud-native/.github/actions/automerge-pr
        with:
          github-token: ${{ secrets.X_GITHUB_CARTOFANTE }}
          github-user: cartofante
          pr-number: ${{ github.event.pull_request.number }}
