name: Release - Autotag
on:
  push:
    branches:
      - master
    paths:
      - VERSION
jobs:
  create-tag:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve Release Version
        id: info
        run: echo "release-version=$(cat VERSION)" >> ${GITHUB_OUTPUT}

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.X_GITHUB_CARTOFANTE }}
          commit: ${{ github.sha }}
          name: ${{ steps.info.outputs.release-version }}
          tag: ${{ steps.info.outputs.release-version }}
          prerelease: true
          body: "Release notes for this version are available at https://docs.carto.com/get-help/deployment-options/self-hosted/release-notes#${{ steps.info.outputs.release-version }}"
